### ISSUE TITLE
Multiple Master Dashlet Support

### ISSUE THREAD

**Issue by ghost** [Dynatrace/Master-Slave-Dashboard-Creator#1]
Thanks to Nishant Rama for this tip. We also have the ability to set multiple masters corresponding to multiple slaves. This would be a manual process at present. Code ability to do this via GUI.

**Comment by adamgardner2015** [comment]
Status: Working on it
Estimated completion: 20/12/2016

**Comment by ghost** [comment]
Resolved with release v2
